### ISSUE TITLE
Getting KeyError: 'current'

### ISSUE THREAD

**Issue by frdayeen** [kotamorishi/weather-impression#3]
Getting an error when tried to run weather.py-

```
Traceback (most recent call last):
  File "/home/pi/weather-impression/weather.py", line 419, in <module>
    update()
  File "/home/pi/weather-impression/weather.py", line 410, in update
    drawWeather(wi, cv)
  File "/home/pi/weather-impression/weather.py", line 190, in drawWeather
    temp_cur = wi.weatherInfo[u'current'][u'temp']
KeyError: 'current'
```
Any fix to solve the problem?

**Comment by frdayeen** [comment]
After some searching, it seems that the openweathermap.org has changed their json format. The free service doesn't offer hourly or daily forecast. The code needed to be modified according to their [json for free service](https://openweathermap.org/current). Alternatively you may subscribe to their _pay as you call_ service which offers 1,000 API calls per day for free.

**Comment by kotamorishi** [comment]
Hi @fridayeen,
This repo is intended to use the [One Call API 3.0](https://openweathermap.org/api/one-call-3) to retrieve the hourly forecast.
https://github.com/kotamorishi/weather-impression#weather-information

If you wish to use the free service, you need to modify the code accordingly. By the way, this project code calls 24 times per day, so you will not be charged.
