### ISSUE TITLE
Feature request: Sunrise / Sunset

### ISSUE THREAD

**Issue by everyplace** [kotamorishi/weather-impression#4]
Hi there,

Thanks for the great project! I’ve started hacking in a new mode to support sunrise and sunset as the bottom section, which I’ve currently pencilled in as “mode 3.” The code is 100% not ok to merge back in right now, but would you be interested in this as a PR?

Check out the test.py file in my fork:
https://github.com/everyplace/weather-impression/tree/feature/sunrise-sunset

-erin

**Comment by everyplace** [comment]
PS if you run it,  note that I still have it in test mode to just output to a png. So far it’s just to prove that everything works, with a next effort to actually lay it out nicely.

**Comment by kotamorishi** [comment]
Hi Erin,

Thanks for the demo code!
![IMG_0393](https://user-images.githubusercontent.com/44553544/221756128-fdbe125b-e361-4d1a-a2e9-db436811966e.jpg)

I would be grateful if you could submit a pull request!!!

Kota

**Comment by everyplace** [comment]
Thanks for checking it out. I will try to clean it up tonight!

**Comment by kotamorishi** [comment]
Thank you so much!
